"""empty message

Revision ID: 7e54da17f6f6
Revises: 
Create Date: 2023-06-06 14:01:13.140559

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7e54da17f6f6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.Column('armyType', sa.String(), nullable=False),
    sa.Column('serialNumber', sa.String(), nullable=False),
    sa.Column('enlistDay', sa.Date(), nullable=False),
    sa.Column('dischargeDay', sa.Date(), nullable=False),
    sa.Column('interesting', sa.String(), nullable=True),
    sa.Column('education', sa.String(), nullable=True),
    sa.Column('certification', sa.String(), nullable=True),
    sa.Column('desiredJob', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    # ### end Alembic commands ###
